[package]
name = "online-result-system"
version = "0.1.0"
authors = ["Omkar Yadav <httpsomkar@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "*"

[dependencies.rocket_contrib]
version = "0.4.1"
default-features = true
features = ["tera_templates"]
